# Copyright 2026 Jens Langecker 
# Licensed under the GNU Affero General Public License v3.0
# see LICENCE.txt of https://www.gnu.org/licenses/agpl-3.0.en.html
# SPDX-License-Identifier: AGPL-3.0-or-later
keydir=keys
extensions_dir=extensions
openssl_binary=bin\openssl
ca_file=<root certificate>
issuer_email=<root certifiate issuer email>
forward_7zip=false
7zip_path=bin\7zr
7zip_chunksize=4g
pw_length=8
