# Configuration file of easy-encrypter
# Copyright 2026 Jens Langecker 
# Licensed under the GNU Affero General Public License v3.0
# see LICENCE.txt of https://www.gnu.org/licenses/agpl-3.0.en.html
# SPDX-License-Identifier: AGPL-3.0-or-later
certificate_file=<certificate-file> # Certificate to use for asymmetric encryption, must be set!
openssl_binary=openssl.exe # Path to OpenSSL binary, suffix .exe is mandatory, must be set!
chunksize=1000 # in MiB. Better than 1024, so we've a bit more space for the header
exp_date=0 # how much days in future the certificate will expire. default 0
bitLength=192 # length of AES-cipher; min: 128, mid: 192, max: 256
